### ISSUE TITLE
Deleting issue

### ISSUE THREAD

**Issue by tmeasday** [tmeasday/meteor-presence#1]
See these in logs, and presences aren't always being deleted:

```
Exception in queued task: Error: Removed nonexistent document
```

I think it's due to using upsert, which I'm not sure is supported.

**Comment by jonjamz** [comment]
Hey is this still an issue with the package?

**Comment by tmeasday** [comment]
Actually, it's not an issue with this package, per se. It's an issue with https://github.com/erundook/meteor-publish-with-relations (I should open one there) related to https://github.com/meteor/meteor/issues/944. 

In short: using presence is fine, but don't use it in combination with p-w-r, for now.

**Comment by tmeasday** [comment]
(When I say don't use it in combination, I mean don't publish presences via PWR, you can use both packages in your project though).

**Comment by jonjamz** [comment]
Oh man, thank you for qualifying that response, because I'm actually in the process of integrating both into my app. :+1:
