### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by nleush** [tmeasday/meteor-presence#13]
Can you create example app?

I've spend 20 minutes and didn't figured out how to use it...

**Comment by dburles** [comment]
hi @nleush which part are you stuck on?

**Comment by nleush** [comment]
I need list or count of online users.
Meteor.presences is empty
new Meteor.Collection('userPresence') is empty too.

**Comment by dburles** [comment]
is this a new project? if you have removed the autopublish package, make sure you have setup the correct publications/subscriptions (see: https://github.com/tmeasday/meteor-presence#usage)

make sure you're subscribing to the publication on the client side

```
Meteor.subscribe('userPresence');
```

**Comment by nleush** [comment]
Thanks... I really forgot about subscribe.

**Comment by dburles** [comment]
no problem.

**Comment by nleush** [comment]
Still not working...

https://github.com/nleush/meteor-todos-sortable-animation/commit/54b0c891ed795f15f12790268e1e34e11e3fa89b

Just uploding new version to todos-dnd-animated.meteor.com

**Comment by dburles** [comment]
ah. you don't need to create a collection, as the collection is referenced through `Meteor.presences` and that is what you use to query on. e.g `Meteor.presences.find().count();`

**Comment by nleush** [comment]
That helped!

Thanks. I'm new in Meteor. Some things not obvious.

**Comment by nleush** [comment]
BTW, cool package!

**Comment by dburles** [comment]
thanks, glad to help :)
