### ISSUE TITLE
What would the copyright be?

### ISSUE THREAD

**Issue by snshn** [tmeasday/meteor-presence#15]
Hello, @tmeasday 
I would like to merge the code from your module into my meteorJS project directly, with no mrt dependency (for easier distribution and installation).
I would also like to keep the collection server-side and only publish record with id "_online" which will serve as a reactive counter client-side, since I only need to display the amount of people online as a counter, not as a list of users.

Could you please tell me what kind of license I should include in with your code in my files?
I respect your work and believe you deserve a credit, even if nobody sees it Ü

Thanks.

**Comment by tmeasday** [comment]
Oh, no problem. I added a license.txt file (MIT)

**Comment by snshn** [comment]
Thanks!
