### ISSUE TITLE
Meteor.Presence.state example?

### ISSUE THREAD

**Issue by samim23** [tmeasday/meteor-presence#16]
I´ve got an app featuring multi-room chat. Now i´m trying to use the custom Meteor.Presence.state to show the count of just the users in a specific room.

Been following your example from the doc´s but can´t get it to work. 
Could you elaborate on this a bit?

Meteor.Presence.state = function() {
  return {
    online: true,
    currentRoomId: Session.get('currentRoomId');
  };
}

**Comment by dburles** [comment]
Just make a query against the presences collection like: Meteor.presences.find({ currentRoomId: ... }).count()

**Comment by samim23** [comment]
if tried this before actually but was confused by the output i got. When outputting the entire presence collection to the console, i do see the currentRoomId inside the "docs" but can´t seem to access the individual value via the find. Any ideas what i´m doing wrong?

**Comment by dburles** [comment]
Oh sorry, my bad! Your query should look like: Meteor.presences.find({ 'state.currentRoomId': ... }) 
That should do it.

**Comment by samim23** [comment]
very cool, works like a charm. Btw. have you looked into using meteor streams for this?

**Comment by dburles** [comment]
Cool. I have heard of streams but I'm pretty sure that it wouldn't make sense here, as one of the main features of presence is maintaining a collection that can be used to query on
