### ISSUE TITLE
Meteor.presences is undefined

### ISSUE THREAD

**Issue by povesteam** [tmeasday/meteor-presence#19]
I have removed the autopublish package, and added the [Meteor.publish from readme](https://github.com/tmeasday/meteor-presence#usage).

Still, Meteor.presences is undefined, and the collection doesn't appear in mongo.

![image](https://f.cloud.github.com/assets/506532/1911019/efb64b5a-7d24-11e3-986c-075f5d5cd950.png)

What did I miss?

Thanks!
Ruben

**Comment by tmeasday** [comment]
Have you definitely added the package? Is it listed in `.meteor/packages`?

**Comment by povesteam** [comment]
I didn't know that `presence` needed to be added to `.meteor/packages`.
I ran `meteor add presence` and it was added there. Apparently `mrt add presence` didn't work for me.

It works well now.

Thanks, Tom!
Ruben
