### ISSUE TITLE
Problems with hot code push

### ISSUE THREAD

**Issue by gabrielhpugliese** [tmeasday/meteor-presence#2]
Whenever I deploy to my server it seems current presences remain stuck and are not removed. I don't really know what's happening but I've debugged a lot.
lastSeen field continues to update forever for all of the documents.
Could you please help to confirm this ? And if it's on hot code push, how could I fix it ?

Thanks in advance.

**Comment by gabrielhpugliese** [comment]
Also, I'm monitoring with Google Analytics real-time to see differences. Now I have 5 users online but in db.presences are showing 16 documents.

**Comment by tmeasday** [comment]
Hey,

I take it they are never cleaned up?

It must be a bug. Can you diagnose why the mongo delete query isn't matching?

In general it probably makes sense to delete all presences on hot-code-push as users get new SessionIds anyway.

**Comment by gabrielhpugliese** [comment]
For my point of view, it duplicates everything that is inside db.presences.
I will try to do a repo that you can clone and reproduce it.

I will try to delete all presences on my app whenever code push happens (http://coderstv.com) to see if it works.

**Comment by gabrielhpugliese** [comment]
Well I can't reproduce it. If I find it I reopen this. Sorry for wasting your time.

**Comment by tmeasday** [comment]
Ok, although I know there _are_ issues here in that extra presences hang around for a while. So I'm going to re-open for that reason.

If you find a case where presences are never deleted in such situations, open a new bug.

**Comment by gabrielhpugliese** [comment]
Actually I've found the (big) problem.

I'm using mini-pages to get what path the user is in. Meteor.router.invocation() is a reactive data source that have the information about the current page.
So, when I try to do this:

``` javascript
    Meteor.Presence.state = function () {
        return {
            online : true,
            currentCoder : Meteor.router.invocation().currentCoder,
            currentVideo : Meteor.router.invocation().currentVideo
        }
    }

Meteor.presences.find().observe({
    added : function (doc) {
        console.log("Entering ADDED!");
        // increment viewers of coder doc.currentCoder
        }
    },
    removed : function (doc) {
        console.log("Entering REMOVE!");
        // decrement viewers from coder doc.currentCoder
        }
    }
});
```

When hot-code-push happens, "Entering ADDED" is printed 4 times when 2 users are online, but "Entering REMOVE" is printed only two times, 5-10 seconds after all the 4 added prints.
So the final count is 2 (initial state) + 4 - 2 = 4.

I tried with other reactive sources and the same issue happens. Removing everything from collection does not work either because the problem is the 4 inserts on observe.

So, I'm exhausted. Been debugging it for hours. If you have any ideas, please tell me how to fix it.
Thanks

**Comment by gabrielhpugliese** [comment]
I've not pasted changed method because it's always called so it's pointless to debug.

**Comment by gabrielhpugliese** [comment]
Another thing I've done without success is put just one reactive source inside the state function. But the same issue is shown :(

**Comment by tmeasday** [comment]
I'm a bit confused about "So the final count is 2 (initial state) + 4 - 2 = 4." 

The way you described it I would have thought the final count (correctly) would be 2.

Why don't you try something simpler like:

``` js
Deps.autorun(function() {
  console.log("There are " + Meteor.presences.find().count() + " users online");
});
```

**Comment by gabrielhpugliese** [comment]
Observe.added is called four times when only two people are on server after
hot code push. It was supposed to be only two times. Maybe we could do a
fast hangout so I can show you live.
Em 14/05/2013 01:24, "Tom Coleman" notifications@github.com escreveu:

**Comment by tmeasday** [comment]
Right, but then `removed` is called twice after 10 seconds when the server realises that the old records are gone.

So for 10 seconds the system thinks 4 users are online (which is wrong and the reason this bug is still open), but then 2.  However, you say "the final state is ... = 4" which is why I'm confused.

**Comment by gabrielhpugliese** [comment]
But you're not counting the initial state that is 2 users. So the math is 2 + 4 - 2

**Comment by gabrielhpugliese** [comment]
The real problem that I've not explicited:

I'm incrementing a document inside added. So, if I already had 2 users in my app, added was already called 2 times so my document was incremented by 2 (doc.count = 2)
When hot-code-push happens, added is called 4 times, incrementing more 4 on my doc (doc.count = 6).
After 10 seconds, it decrements 2 giving me doc.count = 4.

I've done a complete traceback of all methods of observe in hot-code-push (increments and decrements are logged only after they happen. So if they don't happen it does not show):

``` bash
vagrant@precise32:/vagrant/livecode$ => Meteor server restarted
Entering ADDED!
Presences: 2
My doc.count: 3
Entering ADDED!
Presences: 2
My doc.count: 4
Entering ADDED!
Presences: 3
Entering ADDED!
Presences: 4
Entering CHANGED!
My doc.count: 5
Entering CHANGED!
My doc.count: 6
Entering REMOVED
Presences: 2
My doc.count: 5
Entering REMOVED
Presences: 2
My doc.count: 4
```

Here a screencast (sorry for quality and bad english):
http://youtu.be/wUwHpX1ztzE

**Comment by tmeasday** [comment]
It seems like you'll need to reset that counter on HCP as even if presences was working right, I wouldn't expect to see `.removed()` calls for the two existing presences when the browser restarts..

**Comment by gabrielhpugliese** [comment]
Yeah, I didn't want to do that because it looked like a bad pattern to me. But now it makes sense reading your comment.

**Comment by gabrielhpugliese** [comment]
For awareness, my deploy config runs an extra command:

``` bash
mongo $APP_NAME $APP_DIR/$APP_NAME/update.js;
```

That $set watchers to 0 with multi : true

Thanks Tom!

**Comment by tmeasday** [comment]
Oh, cool. You could have done it in a `Meteor.startup` block server-side too...

**Comment by gabrielhpugliese** [comment]
Didn't know it runs on HCP :) Thanks! :+1:
