### ISSUE TITLE
Installation instructions wrong in README

### ISSUE THREAD

**Issue by tragle** [tmeasday/meteor-presence#20]
`mrt add presence` did not install this for me -- it installed the dburles version of meteor-presence. I had to add this repo to the smart.json file and `mrt update` to use it.

The documentation and API's are almost identical, but are different enough to be totally confusing if you don't know which one you're looking at.

**Comment by dburles** [comment]
hey @tragle sorry about the confusion, we have been meaning to update the docs here to highlight that we have moved the package over to https://github.com/dburles/meteor-presence

There's been many improvements since the depart from this version!
