### ISSUE TITLE
compatibility with matteodem:easy-security

### ISSUE THREAD

**Issue by DrPaulBrewer** [tmeasday/meteor-presence#21]
Using both meteor-presence and easy-security for a Ham Radio [Satellite chat](http://satchat.net) room application [here](http://beta.satchat.net) generates a screen of exception too long for Nitrous.io.  

The Meteor.userId vs this.userId issue looks like it is pointing at updatePresence though I have not confirmed in your source code.

Here is some of the exception output that was still visible:

``` I20141124-17:34:22.507(0)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108)                                   
I20141125-12:12:29.678(0)? Exception in setTimeout callback: Error: Meteor.userId can only be invoked in method calls. Use this.
userId in publish functions.                                                                                                    
I20141125-12:12:29.679(0)?     at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19)                           
I20141125-12:12:29.679(0)?     at Meteor.methods.updatePresence (packages/tmeasday:presence/lib/common.js:19)                   
I20141125-12:12:29.680(0)?     at Object.methods.rateLimit.callFunctionsInQueue (packages/matteodem:easy-security/lib/easy-secur
ity.js:72)                                                                                                                      
I20141125-12:12:29.680(0)?     at packages/matteodem:easy-security/lib/easy-security.js:116                                     
I20141125-12:12:29.680(0)?     at packages/matteodem:easy-security/lib/easy-security.js:92                                      
I20141125-12:12:29.680(0)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)                                    
I20141125-12:12:29.681(0)?     at packages/meteor/timers.js:6                                                                   
I20141125-12:12:29.681(0)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108)          
```

[easy-security](https://github.com/matteodem/meteor-easy-security) does throttling of Meteor methods.  

It can be configured.  Here's an example from the above link.

```
EasySecurity.config({
  general: { type: 'rateLimit', ms: 1000 },
  methods: {
     createMethod: { type: 'rateLimit', ms: 1000 * 10 },
     commentMethod: { type: 'throttle', ms: 500 }
  },
  ignoredMethods: ['someOtherMethod'],
  maxQueueLength: 200
});`
```

> There is only 'rateLimit' and 'throttle' available to apply onto Meteor Methods. You can call config by > passing in an object with following optional parameters.
> 
> general Change the general handling of all Meteor.methods
> 
> methods Set specific ways to handle defined methods
> 
> ignoredMethods An array of ignored methods, that means not rateLimit or throttle applied
> 
> debug Boolean if in debug mode or not
> 
> maxQueueLength Resets the queue (per id) after the the length is exceeded

What settings would be required for compatibility between easy-security and meteor-presence?

**Comment by dburles** [comment]
Hey @DrPaulBrewer just so you know the repo lives over at https://github.com/dburles/meteor-presence

I think the problem may be with easy-security as it's perfectly valid to use `Meteor.userId()` within a method. It looks as though easy-security is doing some funny stuff with methods that may be causing that function call to throw that error. Perhaps open an issue over there.

**Comment by DrPaulBrewer** [comment]
I've removed easy-security because I already had implemented anti-repeat and anti-flood.  

@dburles Thanks for the info. I see now the atmospherejs.com page points to the dburles github. Think I came here on a google search.
