### ISSUE TITLE
Mini example

### ISSUE THREAD

**Issue by sammdec** [tmeasday/meteor-presence#3]
Hi Tom, apologies I don't know if this should really be classed as an issue but I was just wondering if there was a small example of how you would add this to a template helper in a project. 

I was also checking to see if it was possible to get a list of all users and check if they are either online of offline

**Comment by tmeasday** [comment]
Sam, I'll try to add something to the readme eventually, but you can just do something like

``` handlebars
{{#each users}}
  {{profile.username}}
  {{#if presence}}
    is Online!
  {{else}
    is not online..
  {{end}}
{{/each}}
```

``` js
Template.foo.users = function() { return Meteor.users.find(); }
Template.foo.presence = function() { return Meteor.presences.findOne({userId: this._id}); }
```
